# Generated by Django 3.2 on 2023-04-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_products_cogs_products_dep_products_interest_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country_code',
            field=models.CharField(default=21, max_length=10),
            preserve_default=False,
        ),
    ]
